UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='10' WHERE (`id`='755');
UPDATE `furniture` SET `interaction_type`='exchange' WHERE (`id`='756');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='20' WHERE (`id`='757');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='50' WHERE (`id`='758');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='5' WHERE (`id`='759');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='500' WHERE (`id`='1145');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='200' WHERE (`id`='1146');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='100' WHERE (`id`='1148');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='50' WHERE (`id`='1149');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='25000' WHERE (`id`='5045');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='1000' WHERE (`id`='5046');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='500' WHERE (`id`='5047');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='250' WHERE (`id`='5048');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='100' WHERE (`id`='5049');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='5000' WHERE (`id`='72021');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='200' WHERE (`id`='445457');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='75' WHERE (`id`='445458');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='300' WHERE (`id`='532591');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='750' WHERE (`id`='540019');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='350' WHERE (`id`='540020');
UPDATE `furniture` SET `interaction_type`='exchange', `behaviour_data`='500' WHERE (`id`='1000000010');

UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet0';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet1';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet2';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet3';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet4';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet5';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet6';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet7';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet8';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet9';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet10';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet11';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet12';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet13';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet14';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet15';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet16';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet17';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet18';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet19';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet20';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet21';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet22';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet23';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet24';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet25';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet26';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet27';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet28';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet29';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet30';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet31';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet32';
UPDATE `furniture` SET `interaction_type` = 'pet' WHERE `interaction_type` = 'pet33';

UPDATE `furniture` SET `behaviour_data`='5' WHERE (`id`='20220');
UPDATE `furniture` SET `behaviour_data`='3' WHERE (`id`='20301');
UPDATE `furniture` SET `behaviour_data`='4' WHERE (`id`='20302');
UPDATE `furniture` SET `behaviour_data`='1' WHERE (`id`='20304');
UPDATE `furniture` SET `behaviour_data`='1' WHERE (`id`='20304');
UPDATE `furniture` SET `behaviour_data`='2' WHERE (`id`='20306');
UPDATE `furniture` SET `behaviour_data`='8' WHERE (`id`='20600');
UPDATE `furniture` SET `behaviour_data`='11' WHERE (`id`='20601');
UPDATE `furniture` SET `behaviour_data`='10' WHERE (`id`='20602');
UPDATE `furniture` SET `behaviour_data`='12' WHERE (`id`='20603');
UPDATE `furniture` SET `behaviour_data`='14' WHERE (`id`='30000');
UPDATE `furniture` SET `behaviour_data`='15' WHERE (`id`='30001');
UPDATE `furniture` SET `behaviour_data`='9' WHERE (`id`='30002');
UPDATE `furniture` SET `behaviour_data`='28' WHERE (`id`='30003');
UPDATE `furniture` SET `behaviour_data`='29' WHERE (`id`='30004');
UPDATE `furniture` SET `behaviour_data`='30' WHERE (`id`='30005');
UPDATE `furniture` SET `behaviour_data`='7' WHERE (`id`='83545');
UPDATE `furniture` SET `behaviour_data`='6' WHERE (`id`='84586');